apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
  namespace: keda-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
      - name: kafka-consumer
        image: strimzi/kafka:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            while true; do
              /opt/kafka/bin/kafka-console-consumer.sh \
                --bootstrap-server ${KAFKA_BROKER} \
                --topic ${KAFKA_TOPIC} \
                --group ${KAFKA_CONSUMER_GROUP} \
                --from-beginning;
              sleep ${SLEEP};
            done
        env:
          - name: "KAFKA_BROKER"
            value: "my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
          - name: "KAFKA_TOPIC"
            value: "keda-topic"
          - name: "KAFKA_CONSUMER_GROUP"
            value: "g1"
          - name: "SLEEP"
            value: "3"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
